### ISSUE TITLE
Deep sleep on BUTTON_2_PIN gets stuck in a loop

### ISSUE THREAD

**Issue by haarts** [paperdink/PaperdInk-Library#14]
When I do `Paperdink.deep_sleep_button_wakeup(BUTTON_2_PIN);` the board is immediately pulled out of sleep resulting in the `setup` code being executed immediately again and again.

When I do `Paperdink.deep_sleep_button_wakeup(BUTTON_1_PIN);` it works as expected. The `setup` code runs once. And when I press the button it runs again.

What is the difference between the pins?

**Comment by rgujju** [comment]
You need to enable pullups for the pins. This will be done by the library now.

```
  pinMode(BUTTON_1_PIN, INPUT_PULLUP);
  pinMode(BUTTON_2_PIN, INPUT_PULLUP);
  pinMode(BUTTON_3_PIN, INPUT_PULLUP);
  pinMode(BUTTON_4_PIN, INPUT_PULLUP);
```
