### ISSUE TITLE
Partial update on Merlot

### ISSUE THREAD

**Issue by yurinnick** [paperdink/PaperdInk-Library#25]
I can't implement partial update/fast refresh on BWR Merlot display, any luck anyone? Based on datasheet I suspect it's not possible in BWR mode, since partial update uses DST2 for NEW bw data. Is there a way to init this display in BW-only mode?

**Comment by rgujju** [comment]
Merlot does not support fast partial update. And there isn't a way to make it BW-only. Only classic supports fast update mode.

**Comment by yurinnick** [comment]
It's kinda a bummer that it wasn't specified anywhere in the press materials. Makes Merlot version pretty useless for me.
